
name: Auto Pull from Original Repo

on:
  repository_dispatch:
    types: [sync-fork]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.email "lvyixuan@njust.edu.cn"
          git config --global user.name "lyu-yx"

      - name: Add remote upstream
        run: git remote add upstream https://github.com/visionxiang/awesome-camouflaged-object-detection.git

      - name: Fetch changes from upstream
        run: git fetch upstream

      - name: Merge changes from upstream main to your fork's main
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
